#druid连接池
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      #主库数据源
       master:
         url: jdbc:mysql:///studydemo11?serverTimezone=UTC
         username: root
         password: 12345678
      #从库数据源
      slave:
        #默认状态，关闭
        enabled: false
        url:
        username:
        password:
      #初始连接数 
      initial-size: 5
      #最小连接池数
      